---
title: "test R script"
author: "Heather Throop"
format: html
editor: visual
---

## Can you see this?

Congrats! You have cloned the repo!

## Running Code

Try running this code:

```{r}
1 + 1
```

## Libraries and File Input

### Load packages

```{r}
#| label: load needed packages
library(here)
library(tidyverse)
```

### Pull in Files from Dropbox

Here we use an example of a Costech file that is stored in the DERT Dropbox (e.g., "230512_UTEP_test.csv" to format data file for analysis). We'll pull this in using the Dropbox link.

```{r}
#| label: read in input data file
### copy the Dropbox link inside of quotes and then change the final number from 0 to 1. 
CN_df <- read.csv("https://www.dropbox.com/scl/fi/atgi3wpwqbuo6a3qqvubr/230512_UTEP_test.csv?rlkey=nqxboqc9y767xxt3b78ov4733&dl=1")
```

## Make a Graph

```{r}
# scatterplot of pctC versus pctN
plot1 <- CN_df |>
  ggplot(aes(x=pctC, y=pctN)) +
    geom_point(shape=1)      # Use hollow circles
plot1

ggsave("ScatterPlot.jpg")
```
